### ISSUE TITLE
TR and ATR

### ISSUE THREAD

**Issue by mihakralj** [mihakralj/QuantLib#12]
@twopirllc @DaveSkender
Inconsistencies of early values between libraries on TR (True Range) and ATR (average True range):

- TA-LIB and Pandas-TA return NaN for the first TR value and have therefore (period+1) of NaN values
- TA-LIB does a SMA([1, period+1]) for the seeding value
- Pandas-TA uses rma(tr) that uses .ewm(tr).mean()
- Skender.Indicators uses RMA() starting from the first value (that's my implementation as well)

- Among three libraries (TA-LIB, Skender.Indicators and Pandas-TA), there is no consensus on what early ATR should be (they all converge eventually):
```
Index      TrueRange       TA-Lib          Skender         Pandas-TA      QuanTAlib
-----------------------------------------------------------------------------------
0          2.025             NaN             NaN             NaN            2.025
1          0.891             NaN             NaN             NaN            1.458
2          2.210             NaN             NaN             NaN            1.709
3          0.296             NaN             NaN             NaN            1.356
4          1.160             NaN           1.317             NaN            1.317
5          2.005           1.313           1.454           1.374            1.454
6          1.553           1.361           1.474           1.423            1.474
7          0.723           1.233           1.324           1.246            1.324
8          0.512           1.089           1.162           1.069            1.162
9          1.297           1.130           1.189           1.122            1.189
10         2.382           1.381           1.427           1.404            1.427
11         3.052           1.715           1.752           1.765            1.752
12         1.778           1.728           1.757           1.768            1.757
13         2.485           1.879           1.903           1.919            1.903
14         0.411           1.585           1.604           1.604            1.604
15         4.338           2.136           2.151           2.171            2.151
16         1.849           2.078           2.091           2.104            2.091
17         2.289           2.120           2.130           2.142            2.130
18         2.886           2.274           2.281           2.294            2.281
19         0.499           1.919           1.925           1.929            1.925
20         0.603           1.655           1.660           1.661            1.660
```

**Comment by DaveSkender** [comment]
Consensus is a funny thing in this space.  My view has always been that too many people just blindly copy someone else’s code or compare to popular charting sites on faith that they’re right.  That propagation may include alternate interpretations or errors … and then be seen as consensus truth by sheer quantity of use.  That’s why I always go back to original author’s explanation and non-code mathematical equations, and never use anyone else’s code as a source of truth.

**Comment by DaveSkender** [comment]
[ATR](https://dotnet.stockindicators.dev/indicators/Atr/#content) and its underlying True Range formula is defined by Welles Wilder in his book “New Concepts in Technical Trading Systems”.  He uses RMA/[SMMA](https://dotnet.stockindicators.dev/indicators/Smma/#content) of TR with an [SMA](https://dotnet.stockindicators.dev/indicators/Sma/#content) initial seed value.  I do the same, so my initial value is literally the first calculable SMA of TR.

In Wilder’s example of his Volatility System, he’s calculating TR in the first period without consideration for prior Close price; one could argue that he should have skipped it, and he does skip it in other examples.  TA-LIB is theoretically more accurate in this regard.

**Comment by mihakralj** [comment]
... and I just realized that I already raised this issue with Pandas-TA: https://github.com/twopirllc/pandas-ta/issues/402

Looks that the PR I made either didn't make it to the release, or I coded something wrong...

**Comment by twopirllc** [comment]
@mihakralj,

Given your recent testing, I assume you have been using PTA _0.3.14b_ (the _main_ branch). The _main_ branch is on hold for the time being until I complete the Hilbert Transform TA Lib indicators: *ht_dcperiod, ht_dcphase, ht_phasor, ht_sine, ht_trendline, ht_trendmode*.

Mind rechecking your results using the development version instead?

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks
KJ

**Comment by DaveSkender** [comment]
> until I complete the Hilbert Transform TA Lib indicators

@twopirllc, lucky you.  Having fun yet, doing all of Ehlers homodyne and heterodynamic discriminations of quadratures and Fourier Euler formulations?  🤣

Makes my head hurt.  Degree in EE needed just to be able to read half of his stuff.  At least he aptly named his book “Rocket Science for Traders”, to be up-front about its complexity.

**Comment by twopirllc** [comment]
@DaveSkender,

> At least he aptly named his book “Rocket Science for Traders”, to be up-front about its complexity.

Yeah. Though I do not have the book which could be helpful. However, the math is not overwhelming for me thankfully.

For the past half year, it has been harder to find the free time to dig into creating, fixing, testing, and replying to the numerous issues.

**Comment by mihakralj** [comment]
> Mind rechecking your results using the development version instead?

I am doing some dark art magic to call Python from within C# managed code, while also injecting the Python.dll at the runtime. 

I can use precompiled wheels from standard pip distribution, but it gets trickier to import/install through git link...

Not as tricky as digesting Ehler's books... I have all three of his works and they make me feel stone-age dumb.

**Comment by DaveSkender** [comment]
I dropped TR in the first period, so should match TA-LIB now in [v2.4.1](https://github.com/DaveSkender/Stock.Indicators/releases/tag/2.4.1%2B44)

**Comment by mihakralj** [comment]
I can now remove the compensation on TR(0) I have put on validation tests. I can confirm that your TR is now equivalent to Tulip, TA-LIB, Pandas-TA and QuanTAlib results.
