### ISSUE TITLE
Strange results - please advise

### ISSUE THREAD

**Issue by gcaplan** [mihakralj/QuantLib#13]
Hi

Potentially a very useful library! As you say, there's a lack of C# resources that handle bar-by-bar live updating efficiently.

I realise it's still very new, but the link to the Getting Started notebook is broken, so it's quite hard to get your head around usage.

I've dug around the source, but there seems to be something I'm missing.

For example I expected the code below to output 4, 5, 6, but I'm seeing:

SMA1: 4
SMA2: 4.333333333333333
SMA3: 4.666666666666667

```
 TSeries vals = new() { 1, 2, 3, 4, 5 };
 SMA_Series sma = new(vals, 3);
 Print.Line("SMA1: " + sma.Last().v);

 vals.Add(6, true);
 Print.Line("SMA2: " + sma.Last().v);

 vals.Add(7, true);
 Print.Line("SMA3: " + sma.Last().v);
```

I didn't see any examples of the update functionality in the test suite so I'm not sure if it's my issue or yours. If I'm misunderstanding something I'd appreciate any pointers.

More generally, it would be great if you could find the time to fix the notebook, or to add some examples to the readme.

Thanks for all your hard work!

**Comment by mihakralj** [comment]
You started with a list of 5 numbers: `{1, 2, 3, 4, 5}` and generate `SMA(3)` on that list.
The return list is `{1, 1.5, 2, 3, 4}`

Now you **REPLACE** the last value in the input list with 6 (the `update: true` parameter is not adding to the list, it is **updating/replacing** the last value) so the input list is now `{1, 2, 3, 4, 6}`, resulting in sma list  `{1, 1.5, 2, 3, 4.3333}`. Mind that the length of input (and output) stayed the same (5 items)

The same happens with **REPLACING** the last value in the input with 7: input is now `{1, 2, 3, 4, 7}` and sma is now `{1, 1.5, 2, 3, 4.667}` - the length stayed the same.

if you want to append numbers to the input, use the default setting of `update: false`.

Why this parameter? When an active bar is forming with ticks, the current value of high/low/close/volume is constantly changing - until the bar is complete and the data stream starts forming a next bar. QuanTAlib allows real-time re-calculation of indicators for this forming bar, updating the indicator whenever the input data updates the last bar.

**Comment by mihakralj** [comment]
uh oh, I have tons of .NET Interactive notebooks that I didn't publish on Github. Would you like that I create a scrap bin and you can rummage through it? They are not pretty but they show the usage...

What I was working on instead is visual comparison of each trend indicator: https://mihakralj.github.io/QuanTAlib/#/SMA

**Comment by gcaplan** [comment]
My bad! Many thanks for your helpful and patient response. I've got things working now.

Any examples would be helpful, even if it's just a scrap bin. I find it easier to learn from code than from docs...
