### ISSUE TITLE
coverage.md updates

### ISSUE THREAD

**Issue by DaveSkender** [mihakralj/QuantLib#6]
A few check marks missing for the `Skender` column:

- LINREG returned with Slope
- ZSCORE returned with Standard Deviation
- LWMA is the same as WMA (duplicate, I think)
- NATR returned with ATR
- ADXR returned with ADX
- AD is same as ADL
- DMI returned with ADX
- TRIX
- CORREL
- TR returned with ATR
- HT Trendline

There’s a few others in the [Skender library](https://daveskender.github.io/Stock.Indicators/indicators/) that aren’t in the list too, but I’m not sure if wanted to add those.  There’s so many out there, I know, it’s hard to choose and prioritize which to add to these sort of libraries.

**Comment by mihakralj** [comment]
Thanks, added/fixed!
I noticed that different TA libraries mix **Population** StdDev/Variance and **Sample** StdDev/Variance - and instead of starting an argument, I rather included both.
I also found out that people don't look 'inside' an indicator to find out what else it returns - so I plan to make all relevant returns independent classes (for example, you packaged MAPE/MAD/MSE within SMA, or TR within ATR)

Anyhow, if you want to peek into the most recent refactoring I did, check the relationship between implementation classes (say WMAPE or BIAS) and their base abstract class (within Abstract_indicators.cs) - that's how I am attempting to avoid code duplication and package all scaffolding into an abstract class - without using Interfaces.

Also relevant for your library: check my validation tests (SMA_Validation.cs) and how I am calling your library to cross-validate results; As I am strict on non-nulls, I have to use a bang (!) to let your nullable results pass without null warning:

`double s1 = Math.Round((double) SKsma.Last().Sma!, 7);`

**Comment by DaveSkender** [comment]
> I noticed that different TA libraries mix **Population** StdDev/Variance and **Sample** StdDev/Variance - and instead of starting an argument, I rather included both.

If I remember back to my school days, I think sampling is only used when you can’t otherwise get data on the full population.  I think most uses cases here are for a discrete known look back window, but can appreciate the option to estimate a larger population.

> I also found out that people don't look 'inside' an indicator to find out what else it returns - so I plan to make all relevant returns independent classes (for example, you packaged MAPE/MAD/MSE within SMA, or TR within ATR)

Yah, some are a bit hidden in my library.  I can probably do better with documentation.  I only bundled for efficiency as they’re calculated together (one pass).  Or add some overrides to make them separate, if anyone ever complains.

> Also relevant for your library: check my validation tests (SMA_Validation.cs) and how I am calling your library to cross-validate results; As I am strict on non-nulls, I have to use a bang (!) to let your nullable results pass without null warning:
> 
> `double s1 = Math.Round((double) SKsma.Last().Sma!, 7);`

Yes, you’d have to deal with the `null`.  How are you handling these incalculable results, are you excluding, returning `NaN`, or just zeroing out?

**Comment by mihakralj** [comment]
when we take 10 samples from the full population of stock prices and calculate Variance or StdDev - does this calculation require Bessel's correction for bias or not? Is it Sample or Population Variance/StdDev? Let traders choose what they want...

Regarding list of indicators - perhaps we gang together and create one unified list of known/implemented indicators, with links to specific source files (or docs)?

Regarding Null values: that's what NaN (not a number) was made for. Null throws exceptions (and makes non-nullable compiler complain), zeros are actual numbers and exclusion would ignore the fact that measurement was created/calculated. NaN can stay in the data, supports all mathematical operations and serves its purpose.

**Comment by mihakralj** [comment]
Using null-forgiving operator:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving

**Comment by DaveSkender** [comment]
> Regarding list of indicators - perhaps we gang together and create one unified list of known/implemented indicators, with links to specific source files (or docs)?

Lol.  For as much fun as that sounds, I'll pass on that.  There's literally thousands of indicators out there and 10x as many really bad source site options to reference.  As you get into this more, you'll find that sources on the internet are quite unreliable.  That and there's probably sites out there already that catalog and try to define all of these.
 
> Regarding Null values: that's what NaN (not a number) was made for. Null throws exceptions (and makes non-nullable compiler complain), zeros are actual numbers and exclusion would ignore the fact that measurement was created/calculated. NaN can stay in the data, supports all mathematical operations and serves its purpose.

We're just going to have to respectfully disagree on `NaN` being better than `null` in this use case 😃; but, I do appreciate that you're considering and handling incalculable results.  You could probably have a little `NullToNan()` helper function to make your life easier when comparing the library output.

**Comment by mihakralj** [comment]
You do you. 

There has been vast amounts written on why [null was the billion dollar mistake](https://en.wikipedia.org/wiki/Tony_Hoare), but to get very specific to C# coding style, Anders Hejlsberg was very clear in an interview why he is on a war path to eradicate null out from the future of C#: "_50% of the bugs that people run into today, coding with C# in our platform, are probably null reference exceptions._"

**Comment by DaveSkender** [comment]
> There has been vast amounts written on why [null was the billion dollar mistake](https://en.wikipedia.org/wiki/Tony_Hoare), but to get very specific to C# coding style, Anders Hejlsberg was very clear in an interview why he is on a war path to eradicate null out from the future of C#: "_50% of the bugs that people run into today, coding with C# in our platform, are probably null reference exceptions._"

I've seen the rhetoric on it and totally agree with the `null` problem, especially in C#.  I think it comes down to intentional design and handling -- if you're not handling it, it is a problem.  `NaN` has the same conundrum.  The big question is, how are we supposed to represent incalculable data?

I've started a learning discussion here: https://github.com/DaveSkender/Stock.Indicators/discussions/767

**Comment by mihakralj** [comment]
Math.Log(Double.NaN) == NaN

Math.Log(null) == error CS1503: Argument 1: cannot convert from '< null >' to 'double'

**Comment by DaveSkender** [comment]
> Math.Log(Double.NaN) == NaN
> 
> Math.Log(null) == error CS1503: Argument 1: cannot convert from '' to 'double'

Yah, that Math library doesn't do nulls.  That is really annoying.  IMO it should work the exact same as `NaN` in that use case.  Most normal math, like `4*null=null`, so you'd expect the same for the Math lib.
