### ISSUE TITLE
The name might be confusing?

### ISSUE THREAD

**Issue by lballabio** [mihakralj/QuantLib#7]
There's already been a QuantLib for the last 20 years, see <https://www.quantlib.org/> — having the same name can confuse users.  Also, it will make your project difficult to find, since Google will point people to the other one.

Best of luck with your project!

**Comment by mihakralj** [comment]
yeah, I noticed, once a garage project turned public that the name (that fits Quantower augmentation so well) is already a known entity...

If I'd change it to QuantLib .NET or QuanTAlib, would you feel it is differentiating enough to not dilute the name of your QuantLib?

**Comment by lballabio** [comment]
QuanTAlib is probably better — I wouldn't have problems with QuantLib.NET, but people (and Google) would probably confuse it with a .NET port of QuantLib.  I didn't mean to hurry you though, just to raise the issue.  Giving it some time, you can probably find a name that you like better and that it's more likely to point to your project in search results.

**Comment by mihakralj** [comment]
Renaming done.

**Comment by lballabio** [comment]
Best of luck again!
